version: '3'

services:
  web:
    build:
      context: .
      dockerfile: dockerfiles/DockerfileRails
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    volumes:
      - .:/myapp
    env_file:
      - ./env/development/app.env
    ports:
      - 3000:3000
    depends_on:
      - db

  proxy:
    build:
      context: .
      dockerfile: dockerfiles/DockerfileWebpack
    command: yarn start
    volumes:
      - .:/myapp
    env_file:
      - ./env/development/app.env
    depends_on:
      - web
    ports:
      - 3002:3002

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - ./env/development/db.env

volumes:
  db-data:
    driver: local