version: '3'

services:
  web:
    build:
      context: .
      dockerfile: dockerfiles/DockerfileRails
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    volumes:
      - .:/myapp
    ports:
      - 3000:3000
