default: &default
  adapter: mysql2
  encoding: utf8

development:
  <<: *default
  database: rails_sample
  pool: 5
  username: root
  password: root
  host: db

test:
  <<: *default
  database: rails_sample_test
  pool: 5
  username: root
  password: root
  host: db

production:
  <<: *default
  database: rails_sample_production
  pool: 5
  username: root
  password: root
  host: db
